### ISSUE TITLE
Duplicating item from main hand & dissapearing

### ISSUE THREAD

**Issue by x3Michels** [TheRedBrain/rpg-inventory#14] opened 2024-07-22 03:37 UTC
So with a few friends we found we can duplicate everything that was on the first slot of the left hand(this is a god thing)
The problem is, can replace other weapons or tools in the inventory slots(really a bad thing)
![image](https://github.com/user-attachments/assets/121f3b1d-5771-4b68-885f-45167be4dc7f)
So The Problem is the "Advanced Feeding Upgrade" from the mod "Sophisticated Backpapcks" and the slot that you leave after changin to the main hand(item are in there.
![image](https://github.com/user-attachments/assets/463b55c5-83c8-4dae-984e-84af65846d6e)
So everytime it eat for being hungry or when hurt, It will be replaced the blank slot or item for the one is on the main hand

https://github.com/user-attachments/assets/9c365cdc-af08-44d2-9af1-1fbde79c4c1e

sorry for the bad quality, I doesnt know where to upload the video for make it easy for you to see..

**Comment by TheRedBrain** [comment] 2024-07-22 09:36
Thank you for the report!

I will investigate.

The videos are a great help, the quality is absolutely okay

**Comment by TheRedBrain** [comment] 2024-07-22 09:53
As far as I can tell there is nothing I can do from my side.

The Feeding Upgrade places the item equipped in the main hand into to currently selected hot bar slot after the feeding.
If the item would be equipped into the main hand slot, everything would work as intended. (as far as I can tell after looking at their code for 5 minutes)

To solve this problem, either an add-on mod is needed or the FeedingUpgradeWrapper#tryFeedingFoodFromStorage method in SophisticatedCore needs to be changed to the behaviour described above.

**Comment by Salandora** [comment] 2024-07-23 21:37
So Looked into the issue and thanks to your analysis it became a pretty easy fix, so should be fixed in the next sophisticatedcore version.

**Comment by TheRedBrain** [comment] 2024-07-23 22:01
oh cool, that's good to hear!
Cheers!

**Closed as completed** 2024-07-24 17:07 UTC
